// perspective_test.go — end-to-end check of the approach-B perspective decode on
// the on-disk testdata/perspective fixtures (generated by internal/fixture/
// genperspective). For each fixture it rebuilds the true redaction, builds a
// rectify.Projector from the photo + manifest quad, and asserts the forward
// model scores the true content low and a wrong candidate clearly higher — i.e.
// generate-and-test still discriminates through a perspective warp.
//
// No build tag: runs in the default suite (the fixtures are small and fast).
package unpixel_test

import (
	"encoding/json"
	"image"
	"image/png"
	"os"
	"path/filepath"
	"testing"

	"github.com/oioio-space/unpixel/internal/fixture"
	"github.com/oioio-space/unpixel/internal/rectify"
)

// perspectiveSpec mirrors one entry in testdata/perspective/manifest.json.
type perspectiveSpec struct {
	Name        string        `json:"name"`
	File        string        `json:"file"`
	Text        string        `json:"text"`
	Charset     string        `json:"charset"`
	FontSize    float64       `json:"font_size"`
	BlockSize   int           `json:"block_size"`
	PaddingTop  int           `json:"padding_top"`
	PaddingLeft int           `json:"padding_left"`
	PhotoW      int           `json:"photo_w"`
	PhotoH      int           `json:"photo_h"`
	Quad        [4][2]float64 `json:"quad"`
}

func (s perspectiveSpec) fixtureSpec() fixture.Spec {
	return fixture.Spec{
		Name: s.Name, Text: s.Text, Charset: s.Charset, FontSize: s.FontSize,
		BlockSize: s.BlockSize, PaddingTop: s.PaddingTop, PaddingLeft: s.PaddingLeft,
	}
}

func (s perspectiveSpec) quad() [4]rectify.Point {
	return [4]rectify.Point{
		{X: s.Quad[0][0], Y: s.Quad[0][1]},
		{X: s.Quad[1][0], Y: s.Quad[1][1]},
		{X: s.Quad[2][0], Y: s.Quad[2][1]},
		{X: s.Quad[3][0], Y: s.Quad[3][1]},
	}
}

func TestPerspectiveForwardModel(t *testing.T) {
	const dir = "testdata/perspective"
	data, err := os.ReadFile(filepath.Join(dir, "manifest.json"))
	if err != nil {
		t.Skipf("no perspective fixtures (%v) — run: go run ./internal/fixture/genperspective", err)
	}
	var specs []perspectiveSpec
	if err := json.Unmarshal(data, &specs); err != nil {
		t.Fatalf("parse manifest: %v", err)
	}
	if len(specs) == 0 {
		t.Fatal("perspective manifest is empty")
	}

	for _, s := range specs {
		t.Run(s.Name, func(t *testing.T) {
			photo := loadPNG(t, filepath.Join(dir, s.File))

			// Rebuild the true redaction (rect space) and a wrong candidate of the
			// same size (inverted colours), then score both via the forward model.
			trueRect, err := fixture.Redact(s.fixtureSpec())
			if err != nil {
				t.Fatalf("redact true: %v", err)
			}
			rw, rh := trueRect.Bounds().Dx(), trueRect.Bounds().Dy()

			proj, err := rectify.NewProjector(photo, s.quad(), rw, rh)
			if err != nil {
				t.Fatalf("NewProjector: %v", err)
			}

			dTrue := proj.Distance(trueRect)
			dWrong := proj.Distance(invertedCopy(trueRect))

			if dTrue > 0.06 {
				t.Errorf("true %q distance = %.4f, want ≤ 0.06 (forward model should match through the warp)", s.Text, dTrue)
			}
			if dWrong <= dTrue+0.05 {
				t.Errorf("wrong candidate distance = %.4f must clearly exceed true %.4f", dWrong, dTrue)
			}
		})
	}
}

func loadPNG(t *testing.T, path string) *image.RGBA {
	t.Helper()
	f, err := os.Open(path) // #nosec G304 — committed testdata
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	defer func() { _ = f.Close() }()
	img, err := png.Decode(f)
	if err != nil {
		t.Fatalf("decode %s: %v", path, err)
	}
	if r, ok := img.(*image.RGBA); ok {
		return r
	}
	b := img.Bounds()
	dst := image.NewRGBA(image.Rect(0, 0, b.Dx(), b.Dy()))
	for y := range b.Dy() {
		for x := range b.Dx() {
			dst.Set(x, y, img.At(b.Min.X+x, b.Min.Y+y))
		}
	}
	return dst
}

func invertedCopy(src *image.RGBA) *image.RGBA {
	b := src.Bounds()
	dst := image.NewRGBA(image.Rect(0, 0, b.Dx(), b.Dy()))
	for i := 0; i+3 < len(src.Pix); i += 4 {
		dst.Pix[i] = 255 - src.Pix[i]
		dst.Pix[i+1] = 255 - src.Pix[i+1]
		dst.Pix[i+2] = 255 - src.Pix[i+2]
		dst.Pix[i+3] = src.Pix[i+3]
	}
	return dst
}
